apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: frontend
  namespace: argocd
spec:
  destination:
    name: in-cluster
    namespace: frontend
  project: default
  source:
    repoURL: https://github.com/uwe-SQUER/infrastructure-provisioning-workshop.git
    targetRevision: main
    path: frontend
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true