apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apps
  namespace: argocd
spec:
  destination:
    name: in-cluster
    namespace: apps
  project: default
  source:
    repoURL: https://github.com/uwe-SQUER/infrastructure-provisioning-workshop.git
    targetRevision: level1
    path: apps
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true